### ISSUE TITLE
The service broker returned an invalid response for the request

### ISSUE THREAD

**Issue by benmccown** [Infra-Red/cf-postgresql-broker#1]
Hello,

I am trying to create the service broker after pushing the app to my Cloud Foundry instance. Every time I try and create the service broker with:

`cf create-service-broker shared-postgresql-broker admin admin http://postgresql-broker.apps-dev.blahblahblah.net --space-scoped`

I get in response:

`Creating service broker shared-postgresql-broker in org test / space postgres-broker-test as admin...                                                             
FAILED
Server error, status code: 502, error code: 10001, message: The service broker returned an invalid response for the request to http://postgresql-broker.apps-dev.blahblahblah.net/v2/catalog. Status Code: 302 Found, Body:
`

I am still learning about Cloud Foundry so I very well may be doing something wrong. Could the issue be the call to v2/catalog? Hoping someone may be able to help. Deploying to Cloud Foundry 2.0

**Comment by Infra-Red** [comment]
Hi @MooseBeanDev !
Could you try to check service broker catalog manually?
```
curl http://admin:admin@postgresql-broker.apps-dev.blahblahblah.net/v2/catalog -H "X-Broker-API-Version: 2.14"
```

Thanks!

**Comment by benmccown** [comment]
Thank you for your response. I am still learning... but also an idiot.

[benmccown@localhost cf-postgresql-broker]$ curl -v http://admin:admin@postgresql-broker.apps-dev.blahblahblah.net/v2/catalog -H "X-Broker-API-Version: 2.14"                                  
*   Trying 10.10.10.33...                                                                                                                                                                   
* TCP_NODELAY set                                                                                                                                                                             
* Connected to postgresql-broker.apps-dev.blahblahblah.net (10.10.10.33) port 80 (#0)                                                                                                        
* Server auth using Basic with user 'admin'                                                                                                                                                   
> GET /v2/catalog HTTP/1.1                                                                                                                                                                    
> Host: postgresql-broker.apps-dev.blahblahblah.net                                                                                                                                            
> Authorization: Basic YWRtaW46YWRtaW4=                                                                                                                                                       
> User-Agent: curl/7.59.0                                                                                                                                                                     
> Accept: */*                                                                                                                                                                                 
> X-Broker-API-Version: 2.14                                                                                                                                                                  
>                                                                                                                                                                                             
* HTTP 1.0, assume close after body                                                                                                                                                           
< HTTP/1.0 302 Found                                                                                                                                                                          
< Location: https://postgresql-broker.apps-dev.blahblahblah.net/v2/catalog                                                                                                                     
< Server: BigIP                                                                                                                                                                               
* HTTP/1.0 connection set to keep alive!                                                                                                                                                      
< Connection: Keep-Alive                                                                                                                                                                      
< Content-Length: 0                                                                                                                                                                           
<                                                                                                                                                                                             
* Connection #0 to host postgresql-broker.apps-dev.blahblahblah.net left intact

After trying again pointed at https

`[benmccown@localhost cf-postgresql-broker]$ cf create-service-broker shared-postgresql-broker admin admin https://postgresql-broker.apps-dev.blahblahblah.net --space-scoped                  
Creating service broker shared-postgresql-broker in org test / space postgres-broker-test as admin...                                                                                 
OK
`

Thank you for your help.
